// @generated by scripts/gen_airports.py — do not edit by hand.
// Re-run the script to refresh from live Polymarket weather markets.

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Airport {
    pub lat: f64,
    pub lon: f64,
    pub elev_m: i32,
    pub display: &'static str,
}

/// Coordinates for every ICAO weather station referenced by an active
/// Polymarket temperature market (snapshot time of last script run).
pub fn lookup(icao: &str) -> Option<&'static Airport> {
    match icao {
        "CYYZ" => Some(&Airport {
            lat: 43.68,
            lon: -79.63,
            elev_m: 173,
            display: "Toronto",
        }),
        "DNMM" => Some(&Airport {
            lat: 6.577,
            lon: 3.321,
            elev_m: 41,
            display: "Lagos",
        }),
        "EDDM" => Some(&Airport {
            lat: 48.35,
            lon: 11.79,
            elev_m: 453,
            display: "Munich",
        }),
        "EFHK" => Some(&Airport {
            lat: 60.32,
            lon: 24.96,
            elev_m: 55,
            display: "Helsinki",
        }),
        "EGLC" => Some(&Airport {
            lat: 51.51,
            lon: 0.05528,
            elev_m: 6,
            display: "London",
        }),
        "EHAM" => Some(&Airport {
            lat: 52.31,
            lon: 4.764,
            elev_m: -3,
            display: "Amsterdam",
        }),
        "EPWA" => Some(&Airport {
            lat: 52.17,
            lon: 20.97,
            elev_m: 110,
            display: "Warsaw",
        }),
        "FACT" => Some(&Airport {
            lat: -33.97,
            lon: 18.6,
            elev_m: 46,
            display: "Cape Town",
        }),
        "KATL" => Some(&Airport {
            lat: 33.64,
            lon: -84.43,
            elev_m: 313,
            display: "Atlanta",
        }),
        "KAUS" => Some(&Airport {
            lat: 30.2,
            lon: -97.66,
            elev_m: 165,
            display: "Austin",
        }),
        "KBKF" => Some(&Airport {
            lat: 39.7,
            lon: -104.8,
            elev_m: 1726,
            display: "Denver",
        }),
        "KDAL" => Some(&Airport {
            lat: 32.84,
            lon: -96.85,
            elev_m: 148,
            display: "Dallas",
        }),
        "KHOU" => Some(&Airport {
            lat: 29.65,
            lon: -95.28,
            elev_m: 14,
            display: "Houston",
        }),
        "KLAX" => Some(&Airport {
            lat: 33.94,
            lon: -118.4,
            elev_m: 38,
            display: "Los Angeles",
        }),
        "KLGA" => Some(&Airport {
            lat: 40.78,
            lon: -73.87,
            elev_m: 6,
            display: "New York City",
        }),
        "KMIA" => Some(&Airport {
            lat: 25.8,
            lon: -80.29,
            elev_m: 2,
            display: "Miami",
        }),
        "KORD" => Some(&Airport {
            lat: 41.98,
            lon: -87.9,
            elev_m: 207,
            display: "Chicago",
        }),
        "KSEA" => Some(&Airport {
            lat: 47.45,
            lon: -122.3,
            elev_m: 132,
            display: "Seattle",
        }),
        "KSFO" => Some(&Airport {
            lat: 37.62,
            lon: -122.4,
            elev_m: 4,
            display: "San Francisco",
        }),
        "LEMD" => Some(&Airport {
            lat: 40.49,
            lon: -3.572,
            elev_m: 609,
            display: "Madrid",
        }),
        "LFPB" => Some(&Airport {
            lat: 48.96,
            lon: 2.437,
            elev_m: 66,
            display: "Paris",
        }),
        "LIMC" => Some(&Airport {
            lat: 45.63,
            lon: 8.728,
            elev_m: 234,
            display: "Milan",
        }),
        "LLBG" => Some(&Airport {
            lat: 32.01,
            lon: 34.89,
            elev_m: 41,
            display: "Tel Aviv",
        }),
        "LTAC" => Some(&Airport {
            lat: 40.13,
            lon: 33.0,
            elev_m: 952,
            display: "Ankara",
        }),
        "LTFM" => Some(&Airport {
            lat: 41.27,
            lon: 28.73,
            elev_m: 99,
            display: "Istanbul",
        }),
        "MMMX" => Some(&Airport {
            lat: 19.44,
            lon: -99.07,
            elev_m: 2230,
            display: "Mexico City",
        }),
        "MPMG" => Some(&Airport {
            lat: 8.973,
            lon: -79.56,
            elev_m: 9,
            display: "Panama City",
        }),
        "NZWN" => Some(&Airport {
            lat: -41.33,
            lon: 174.8,
            elev_m: 12,
            display: "Wellington",
        }),
        "OEJN" => Some(&Airport {
            lat: 21.68,
            lon: 39.16,
            elev_m: 15,
            display: "Jeddah",
        }),
        "OPKC" => Some(&Airport {
            lat: 24.91,
            lon: 67.16,
            elev_m: 30,
            display: "Karachi",
        }),
        "RCSS" => Some(&Airport {
            lat: 25.07,
            lon: 121.6,
            elev_m: 5,
            display: "Taipei",
        }),
        "RJTT" => Some(&Airport {
            lat: 35.55,
            lon: 139.8,
            elev_m: 11,
            display: "Tokyo",
        }),
        "RKPK" => Some(&Airport {
            lat: 35.18,
            lon: 128.9,
            elev_m: 2,
            display: "Busan",
        }),
        "RKSI" => Some(&Airport {
            lat: 37.47,
            lon: 126.5,
            elev_m: 7,
            display: "Seoul",
        }),
        "RPLL" => Some(&Airport {
            lat: 14.51,
            lon: 121.0,
            elev_m: 23,
            display: "Manila",
        }),
        "SAEZ" => Some(&Airport {
            lat: -34.82,
            lon: -58.54,
            elev_m: 20,
            display: "Buenos Aires",
        }),
        "SBGR" => Some(&Airport {
            lat: -23.43,
            lon: -46.47,
            elev_m: 750,
            display: "Sao Paulo",
        }),
        "UUWW" => Some(&Airport {
            lat: 55.59,
            lon: 37.26,
            elev_m: 209,
            display: "Moscow",
        }),
        "VHHH" => Some(&Airport {
            lat: 22.31,
            lon: 113.9,
            elev_m: 9,
            display: "Hong Kong",
        }),
        "VILK" => Some(&Airport {
            lat: 26.76,
            lon: 80.89,
            elev_m: 125,
            display: "Lucknow",
        }),
        "WIHH" => Some(&Airport {
            lat: -6.267,
            lon: 106.9,
            elev_m: 26,
            display: "Jakarta",
        }),
        "WMKK" => Some(&Airport {
            lat: 2.746,
            lon: 101.7,
            elev_m: 21,
            display: "Kuala Lumpur",
        }),
        "WSSS" => Some(&Airport {
            lat: 1.35,
            lon: 104.0,
            elev_m: 7,
            display: "Singapore",
        }),
        "ZBAA" => Some(&Airport {
            lat: 40.08,
            lon: 116.6,
            elev_m: 35,
            display: "Beijing",
        }),
        "ZGGG" => Some(&Airport {
            lat: 23.39,
            lon: 113.3,
            elev_m: 15,
            display: "Guangzhou",
        }),
        "ZGSZ" => Some(&Airport {
            lat: 22.64,
            lon: 113.8,
            elev_m: 4,
            display: "Shenzhen",
        }),
        "ZHHH" => Some(&Airport {
            lat: 30.77,
            lon: 114.2,
            elev_m: 34,
            display: "Wuhan",
        }),
        "ZSPD" => Some(&Airport {
            lat: 31.14,
            lon: 121.8,
            elev_m: 4,
            display: "Shanghai",
        }),
        "ZSQD" => Some(&Airport {
            lat: 36.36,
            lon: 120.1,
            elev_m: 9,
            display: "Qingdao",
        }),
        "ZUCK" => Some(&Airport {
            lat: 29.71,
            lon: 106.7,
            elev_m: 416,
            display: "Chongqing",
        }),
        "ZUUU" => Some(&Airport {
            lat: 30.56,
            lon: 103.9,
            elev_m: 495,
            display: "Chengdu",
        }),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup_hits_known_icao() {
        let a = lookup("KSEA").expect("KSEA must be present");
        assert!((a.lat - 47.45).abs() < 0.5);
        assert!((a.lon + 122.31).abs() < 0.5);
        assert_eq!(a.display, "Seattle");
    }

    #[test]
    fn lookup_misses_unknown() {
        assert!(lookup("XXXX").is_none());
    }

    #[test]
    fn lookup_includes_noaa_prose_stations() {
        for icao in ["LLBG", "UUWW", "LTFM", "VHHH"] {
            assert!(lookup(icao).is_some(), "missing {}", icao);
        }
    }
}
