#!/usr/bin/env python3
"""
Regenerate src/weather/airports.rs from live Polymarket weather markets +
the OurAirports public-domain CSV.

Usage:
    python3 scripts/gen_airports.py

Run this whenever a new weather market appears with an unknown ICAO (the TUI
flashes a warning when it hits one). The output is committed alongside the
script — there is no runtime dependency on the CSV.
"""

from __future__ import annotations

import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

GAMMA_URL = (
    "https://gamma-api.polymarket.com/events"
    "?tag_slug=weather&closed=false&limit=500"
)
OURAIRPORTS_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "weather" / "airports.rs"

# Cities Polymarket resolves via NOAA / HKO rather than Wunderground. Keep in
# sync with country_icao_from_prose() in src/weather/location.rs.
PROSE_OVERRIDES = {
    "LLBG": "Tel Aviv",
    "UUWW": "Moscow",
    "LTFM": "Istanbul",
    "VHHH": "Hong Kong",
}

URL_RE = re.compile(
    r"wunderground\.com/history/daily/([a-z]{2})/[A-Za-z0-9%-]+(?:/[A-Za-z0-9%-]+)?/([A-Z0-9]{3,4})"
)
QUESTION_RE = re.compile(r"(?i)temperature in ([^?]+?) be")

UA = {"user-agent": "poly-cli gen_airports/1.0"}


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def collect_icaos() -> dict[str, str]:
    """Return {icao: display_city}."""
    print(f"[1/3] fetching {GAMMA_URL}", file=sys.stderr)
    data = fetch(GAMMA_URL)
    import json

    events = json.loads(data)
    icaos: dict[str, str] = {}
    market_count = 0
    for ev in events:
        for m in ev.get("markets", []):
            q = m.get("question") or ""
            desc = m.get("description") or ""
            if "temperature" not in q.lower():
                continue
            market_count += 1
            url_match = URL_RE.search(desc)
            q_match = QUESTION_RE.search(q)
            if not url_match or not q_match:
                continue
            icao = url_match.group(2)
            city = q_match.group(1).strip()
            icaos.setdefault(icao, city)
    print(
        f"      {len(events)} events, {market_count} temperature markets, "
        f"{len(icaos)} ICAOs from URLs",
        file=sys.stderr,
    )
    for icao, city in PROSE_OVERRIDES.items():
        icaos.setdefault(icao, city)
    print(f"      + {len(PROSE_OVERRIDES)} NOAA/HKO overrides", file=sys.stderr)
    return icaos


def lookup_coords(icaos: dict[str, str]) -> list[tuple[str, str, float, float, int]]:
    """Return [(icao, display, lat, lon, elev_m), ...] sorted by ICAO."""
    print(f"[2/3] downloading OurAirports CSV", file=sys.stderr)
    csv_bytes = fetch(OURAIRPORTS_URL)
    reader = csv.DictReader(io.StringIO(csv_bytes.decode()))
    found: dict[str, tuple[float, float, int]] = {}
    for row in reader:
        ident = row.get("ident") or ""
        if ident in icaos:
            try:
                lat = float(row["latitude_deg"])
                lon = float(row["longitude_deg"])
                elev_ft = float(row["elevation_ft"]) if row.get("elevation_ft") else 0.0
                elev_m = round(elev_ft * 0.3048)
            except ValueError:
                continue
            found[ident] = (lat, lon, elev_m)

    missing = sorted(set(icaos) - set(found))
    if missing:
        print(f"      WARNING: not in OurAirports: {missing}", file=sys.stderr)
    print(f"      matched {len(found)}/{len(icaos)} ICAOs", file=sys.stderr)

    return sorted(
        [
            (icao, icaos[icao], lat, lon, elev_m)
            for icao, (lat, lon, elev_m) in found.items()
        ]
    )


def emit(rows: list[tuple[str, str, float, float, int]]) -> str:
    lines = [
        "// @generated by scripts/gen_airports.py — do not edit by hand.",
        "// Re-run the script to refresh from live Polymarket weather markets.",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq)]",
        "pub struct Airport {",
        "    pub lat: f64,",
        "    pub lon: f64,",
        "    pub elev_m: i32,",
        "    pub display: &'static str,",
        "}",
        "",
        "/// Coordinates for every ICAO weather station referenced by an active",
        "/// Polymarket temperature market (snapshot time of last script run).",
        "pub fn lookup(icao: &str) -> Option<&'static Airport> {",
        "    match icao {",
    ]
    for icao, display, lat, lon, elev_m in rows:
        lines.append(
            f'        "{icao}" => Some(&Airport {{ lat: {lat:.4}, lon: {lon:.4}, '
            f'elev_m: {elev_m}, display: "{display}" }}),'
        )
    lines += [
        "        _ => None,",
        "    }",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn lookup_hits_known_icao() {",
        '        let a = lookup("KSEA").expect("KSEA must be present");',
        "        assert!((a.lat - 47.45).abs() < 0.5);",
        "        assert!((a.lon + 122.31).abs() < 0.5);",
        '        assert_eq!(a.display, "Seattle");',
        "    }",
        "",
        "    #[test]",
        "    fn lookup_misses_unknown() {",
        '        assert!(lookup("XXXX").is_none());',
        "    }",
        "",
        "    #[test]",
        "    fn lookup_includes_noaa_prose_stations() {",
        '        for icao in ["LLBG", "UUWW", "LTFM", "VHHH"] {',
        "            assert!(lookup(icao).is_some(), \"missing {}\", icao);",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    icaos = collect_icaos()
    rows = lookup_coords(icaos)
    if not rows:
        print("error: no rows to emit", file=sys.stderr)
        return 1
    src = emit(rows)
    OUTPUT.write_text(src)
    print(f"[3/3] wrote {OUTPUT} ({len(rows)} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
